apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-bot
spec: 
  schedule: "0 9,12,15 * * *"
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: weather-bot
            image: weather-bot
            imagePullPolicy: IfNotPresent
            command: ["python3"]
            args: ["weather.py"]
          restartPolicy: OnFailure
