apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world
spec: 
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: hello-world
            image: hello-world
            imagePullPolicy: IfNotPresent
            command: ["python3"]
            args: ["hello-world.py"]
          restartPolicy: OnFailure
