apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-bot
spec: 
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: weather-bot
            image: weather-bot
            imagePullPolicy: IfNotPresent
            command: ["python3"]
            args: ["weather.py"]
            envFrom:
            - configMapRef:
                name: weather-config
            - secretRef:
                name: weather-secret
          restartPolicy: Never
     